-- Supabase table schema for TheSubhub Order Tracker
-- Run this in Supabase SQL editor or via psql to create the orders table.

create table if not exists orders (
  id bigint generated by default as identity primary key,
  name text not null,
  product text not null,
  cost numeric(12,2) not null default 0,
  sell numeric(12,2) not null default 0,
  end_date date not null,
  duration_label text,
  notified boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists orders_end_date_idx on orders (end_date);
create index if not exists orders_created_at_idx on orders (created_at);

-- If row-level security is enabled, create policies to allow server-side insert/select.
-- Run this in Supabase SQL editor if needed.

alter table orders enable row level security;

create policy if not exists allow_public_select on orders
  for select
  using (true);

create policy if not exists allow_public_insert on orders
  for insert
  with check (true);
